In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving 4_resultados_agua.csv to 4_resultados_agua (1).csv

In [8]:
import pandas as pd

datos = pd.read_csv("4_resultados_agua.csv")

In [9]:
datos.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='object')

In [10]:
datos.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [11]:
datos[datos["pH"] > 8.5]

Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio]
Index: []

In [12]:
datos[datos["Temp"] > 25]

  Punto   Temp    pH  OD_promedio
4     E  25.15  7.25          5.0

In [13]:
datos[datos["OD_promedio"] < 5]

  Punto  Temp    pH  OD_promedio
2     C  19.8  6.85          4.9

In [14]:
datos[(datos["pH"] > 8.5) & (datos["Temp"] > 25)]

Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio]
Index: []

In [15]:
datos[(datos["pH"] < 6.5) | (datos["OD_promedio"] < 5)]

  Punto  Temp    pH  OD_promedio
2     C  19.8  6.85          4.9

In [16]:
def clasificar(fila):
    if fila["pH"] > 8.5 and fila["Temp"] > 25:
        return "Critico"
    elif fila["OD_promedio"] < 5:
        return "Bajo Oxigeno"
    else:
        return "Normal"

datos["Categoria"] = datos.apply(clasificar, axis=1)

In [17]:
datos.head()

  Punto   Temp    pH  OD_promedio     Categoria
0     A  22.25  7.15          6.2        Normal
1     B  24.30  7.20          5.8        Normal
2     C  19.80  6.85          4.9  Bajo Oxigeno
3     D  23.65  7.05          6.5        Normal
4     E  25.15  7.25          5.0        Normal

In [18]:
datos["Categoria"].value_counts()

Categoria
Normal          4
Bajo Oxigeno    1
Name: count, dtype: int64

In [19]:
datos.to_csv("reto2_resultado.csv", index=False)

Reto 2 – Filtros y condiciones en Pandas
Descripción general.

En este ejercicio se trabajó con Pandas para analizar el archivo 4_resultados_agua.csv, que contiene variables asociadas a la calidad del agua en diferentes puntos de una muestra específica.

El objetivo principal fue aplicar filtros condicionales y operadores lógicos para identificar registros específicos de valores como pH, temperatura y oxígeno disuelto, además de generar una nueva clasificación automática de los datos.