In [22]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [23]:
import pandas as pd

datos = pd.read_csv('4_resultados_agua.csv')

datos['categoria_ph'] = pd.cut(
    datos['pH'],
    bins=[0, 6.5, 8.5, 14],
    labels=['Ácido', 'Neutro', 'Básico']
)

datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

In [24]:
datos.mean(numeric_only=True)

Temp           23.03
pH              7.10
OD_promedio     5.68
dtype: float64

In [25]:
datos.groupby('categoria_ph').mean(numeric_only=True)

               Temp   pH  OD_promedio
categoria_ph
Neutro        23.03  7.1         5.68

In [26]:
agua_acida = datos[datos['categoria_ph'] == 'Ácido']
agua_neutra = datos[datos['categoria_ph'] == 'Neutro']
agua_basica = datos[datos['categoria_ph'] == 'Básico']

print("Muestras ácidas:")
print(agua_acida.head())

print("\nMuestras neutras:")
print(agua_neutra.head())

print("\nMuestras básicas:")
print(agua_basica.head())

Muestras ácidas:
Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio, categoria_ph]
Index: []

Muestras neutras:
  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

Muestras básicas:
Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio, categoria_ph]
Index: []

In [27]:
resumen = datos.select_dtypes(include='number').groupby(datos['categoria_ph']).agg(['mean', 'min', 'max'])

print(resumen)

               Temp                pH             OD_promedio
               mean   min    max mean   min   max        mean  min  max
categoria_ph
Neutro        23.03  19.8  25.15  7.1  6.85  7.25        5.68  4.9  6.5

Se realizó un filtrado independiente para cada categoría de pH (ácido, neutro y básico), con el fin de analizar sus características específicas. Posteriormente, se generó un resumen estadístico agrupado, obteniendo valores promedio, mínimos y máximos para cada categoría.

## 📌 Introducción

En este trabajo se analiza la calidad del agua a partir de un conjunto de datos, utilizando la biblioteca pandas en Python. El objetivo es aplicar técnicas de análisis de datos como lectura de archivos, filtrado, clasificación y cálculo de estadísticas, con el fin de interpretar las condiciones del agua según su nivel de pH.