In [12]:
from google.colab import files
uploaded = files.upload()

Saving 4_resultados_agua.csv to 4_resultados_agua (3).csv

In [13]:
import pandas as pd

datos = pd.read_csv('4_resultados_agua.csv')
datos.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [14]:
datos.info()
datos.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      object
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), object(1)
memory usage: 292.0+ bytes

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

In [15]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

In [16]:
agua_acida = datos[datos['categoria_ph'] == 'Ácido']
agua_acida.head()

Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio, categoria_ph]
Index: []

In [17]:
datos.mean(numeric_only=True)

Temp           23.03
pH              7.10
OD_promedio     5.68
dtype: float64

In [18]:
datos['pH'].mean()

np.float64(7.1)

In [19]:
datos.groupby('categoria_ph').mean(numeric_only=True)

               Temp   pH  OD_promedio
categoria_ph
Neutro        23.03  7.1         5.68

In [20]:
datos['calidad'] = datos['pH'] * 10  # ejemplo simple

In [21]:
datos['ph_normalizado'] = (datos['pH'] - datos['pH'].mean()) / datos['pH'].std()

In [22]:
resumen = datos.groupby('categoria_ph').agg({
    'pH': ['mean', 'min', 'max'],
})
resumen

               pH
             mean   min   max
categoria_ph
Neutro        7.1  6.85  7.25

## 📌 Introducción

En este trabajo se analiza la calidad del agua a partir de un conjunto de datos, utilizando la biblioteca pandas en Python. El objetivo es aplicar técnicas de análisis de datos como lectura de archivos, filtrado, clasificación y cálculo de estadísticas, con el fin de interpretar las condiciones del agua según su nivel de pH.